# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-08 03:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userticketmodel',
            name='ticket_out_time',
            field=models.DateField(),
        ),
    ]
